/** Loads data/animals.json (generated by scripts/build-animals-json.mjs). */

/** @type {{ id: string, name: string, imageUrl: string, thumbUrl: string, direction?: 'left'|'right'|'up'|'down' }[] | null} */
let animals = null;

export async function loadCatalog() {
  const url = new URL('../data/animals.json', import.meta.url);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Could not load animal catalog (${res.status}).`);
  const data = await res.json();
  if (!Array.isArray(data.animals) || data.animals.length === 0) {
    throw new Error('Animal catalog is empty.');
  }
  animals = data.animals;
}

/**
 * @param {string[]} excludeIds — commons page ids to omit (e.g. already in album)
 */
export function pickRandomAnimal(excludeIds = []) {
  if (!animals?.length) return null;
  const set = new Set(excludeIds);
  const pool = animals.filter((a) => !set.has(a.id));
  const list = pool.length ? pool : animals;
  return list[Math.floor(Math.random() * list.length)];
}
