/** Loads data/animals.json (generated by scripts/build-animals-json.mjs). */

/** @type {{ id: string, name: string, imageUrl: string, thumbUrl: string }[] | null} */
let animals = null;

export async function loadCatalog() {
  const url = new URL('../data/animals.json', import.meta.url);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Could not load animal catalog (${res.status}).`);
  const data = await res.json();
  if (!Array.isArray(data.animals) || data.animals.length === 0) {
    throw new Error('Animal catalog is empty.');
  }
  animals = data.animals;
}

/**
 * @param {string | null} excludeId — commons page id of last animal (avoid immediate repeat)
 */
export function pickRandomAnimal(excludeId = null) {
  if (!animals?.length) return null;
  const pool = excludeId ? animals.filter((a) => a.id !== excludeId) : animals;
  const list = pool.length ? pool : animals;
  return list[Math.floor(Math.random() * list.length)];
}
